# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 
   
    
    - name: Install dependencies
      run: npm install --save-dev @babel/plugin-proposal-private-property-in-object 
      
      
    - name: Build
      run: npm run build
      env:
       CI: false 
    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-front .
      
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-front      

  run-docker-image-on-ec2:
    runs-on: self-hosted
    steps:
    - name: docker pull
      run : docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-front

    - name: docker stop container
      run: |
        if [ $( docker ps -a -q -f name=ecommerce-front) ]; then
           docker stop ecommerce-front
        fi

    - name: docker run new container
      run: docker run --rm -it -d -p 3000:3000 --name ecommerce-front ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-front

    - name: delete old docker image
      run: docker system prune -f     
   

       
   
                          
                                
                     
        
 
      
    
