# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
     
    - run: npm install 
    - run: npm run build 
   

 

    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-front .
      
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-front      

  run-docker-image-on-ec2:
    runs-on: self-hosted
    steps:
    - name: docker pull
      run : docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-project

    - name: docker stop container
      run: |
        if [ $( docker ps -a -q -f name=ecommerce-project) ]; then
           docker stop ecommerce-project
        fi

    - name: docker run new container
      run: docker run --rm -it -d -p 8080:8080 --name ecommerce-project ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-project

    - name: delete old docker image
      run: docker system prune -f     
   

       
   
                          
                                
                     
        
 
      
    
